Données M52 sont transformées en hierarchiques + composant Sunburst
datalocale/dataviz-finances-gironde pull request #10
Opened 2017-01-15 18:54 UTC by DavidBruant

Fixes #4 
Fixes #5

2017-01-16 17:04 UTC, thom4parisot requested changes

2017-01-16 17:04 UTC, oncletom commented on client/js/components/HierarchicSlice.js
> +export default function HierarchicSlice(props){
Du coup peut être utile de documenter `HierarchicSlice.propTypes` ([cf. doc](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)) pour décrire la structure de props.

Ça sert juste au dev mais ça permettrait de mieux documenter les structures employées.

2017-01-16 17:04 UTC, oncletom commented on client/js/components/M52Viz.js
> +import hierarchicalM52 from '../finance/hierarchicalM52.js';
J'ai pas encore regardé ce fichier mais j'imagine qu'à terme ça peut devenir son propre module npm ? Je vois bien tout l'outillage de simplification de nomenclature, d'analyse de dataset uniquement recracher les données fournies – ensuite mises en forme via d3 (dans notre cas présent).

C'est pas essentiel à ce stade mais si c'est pertinent, c'est à garder dans un coin de la tête en terme de design d'API.

2017-01-16 17:04 UTC, oncletom commented on client/js/components/Sunburst.js
> +export default function(props){
Idem pour les [propTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html).

2017-01-16 17:04 UTC, oncletom commented on client/js/finance/hierarchicalM52.js
> +export default function(rows) {
Vu de l'intérieur, l'intention de ce module n'est pas claire en première lecture. Je sais que ça accepte des données M52 mais je ne suis pas sûr de suivre l'objet des transformations.

2017-01-16 17:04 UTC, oncletom commented on client/js/main.js
> +import afterCSVCleanup from './finance/afterCSVCleanup.js'
_Ça fait quoi_ plus que _Quand c'est à exécuter_ ?

En disséquant le code, je ne suis pas sûr de comprendre pourquoi c'est la seule fonction autorisée à muter les données, ni encore pourquoi elle le fait.

2017-01-24 09:55 UTC, DavidBruant commented on client/js/components/HierarchicSlice.js
> +export default function HierarchicSlice(props){
Yep. Re la discussion que nous avons eu, soit on part sur des PropTypes, soit on part sur du TypeScript qui [d'expérience](https://github.com/anthill/6bin/blob/092582988024a734ffefae82817675fe8676fb79/ts/client/Components/Dumb/BinList.ts#L10-L26) se marie très bien. 
https://github.com/dtc-innovation/dataviz-finances-gironde/issues/18

Pour le moment, j'ai fait de la doc sous la forme d'une interface TypeScript en commentaire.

2017-01-24 09:57 UTC, DavidBruant commented on client/js/components/M52Viz.js
> +import hierarchicalM52 from '../finance/hierarchicalM52.js';
https://github.com/dtc-innovation/dataviz-finances-gironde/issues/19

2017-01-24 10:10 UTC, DavidBruant commented on client/js/main.js
> +import afterCSVCleanup from './finance/afterCSVCleanup.js'
C'est un "workflow":

1. on récupère le texte du CSV
2. on le parse (on a des objets mutables par défaut)
3. on nettoie/uniformise les données (mutations)

2017-01-24 10:10 UTC, DavidBruant commented
Sauf s'il y a un truc majeur, je pense qu'on peut merge ?

2017-01-24 11:06 UTC, oncletom commented on client/js/components/HierarchicSlice.js
> +export default function HierarchicSlice(props){
👍

2017-01-24 11:07 UTC, oncletom commented
Oui :-)

2017-01-24 11:07 UTC, thom4parisot approved these changes

2017-01-24 11:07 UTC, merged