Ajout d'un editorconfig, eslintrc et d'un serveur intégré
datalocale/dataviz-finances-gironde pull request #17
Opened 2017-01-23 12:51 UTC by oncletom

Permet de démarrer avec npm start

2017-01-24 10:16 UTC, DavidBruant commented on .eslintrc.js
> +module.exports = {
J'ai une grosse grosse préférence pour yml

2017-01-24 10:17 UTC, DavidBruant commented on package.json
> +    "eslint": "^3.14.0",
;-)

2017-01-24 10:18 UTC, DavidBruant commented on .editorconfig
> +root = true
C'est quoi ce fichier ? 
Il s'applique à qui ?
Faut-il vraiment forcer la même configuration à tout le monde ?

J'ai l'impression que la grosse majorité des choses ci-dessous sont gérées par `eslint --fix` (sauf peut-être le charset)

2017-01-24 11:03 UTC, oncletom commented on .editorconfig
> +root = true
Ça c'est fait pour que nos IDE utilisent les mêmes standards lors de l'écriture.
> http://editorconfig.org/

Pas besoin de lancer manuellement le `--fix`, potentiellement lancé après un commit (donc pollution inutile de l'historique).

Mon IDE a 2 espaces par défaut, le tiens 4. Dans ce projet mon IDE a 4 espaces par défaut avec la présence de ce fichier.

2017-01-24 11:12 UTC, oncletom commented on .eslintrc.js
> +module.exports = {
Je le remets en yaml.

2017-01-24 11:20 UTC, oncletom commented on package.json
> +    "eslint": "^3.14.0",
Oui ! Dans mon IDE, sans le fichier `.eslintrc.xx` il n'indiquait aucune erreur de syntaxe :-(

2017-01-24 11:37 UTC, DavidBruant commented on package.json
> +    "eslint": "^3.14.0",
hein ? Nan, y'a pas d'erreur je crois, c'est juste que ça fait écho à notre discussion récente sur rajouter eslint en local

2017-01-24 11:38 UTC, DavidBruant requested changes
Concernant ESLint, il manque au moins un .eslintignore avec node_modules et browserify-bundle.js

2017-01-24 12:59 UTC, oncletom commented on package.json
> +    "eslint": "^3.14.0",
Ce que je veux dire (entre autre) c'est qu'il était déjà listé dans les dépendances 😄 (ça a bumpé la version quand j'ai refais l'install).

Atom a un linter intégré qui dépend :

1. de la version locale d'eslint
2. de la présence d'un fichier `.eslintrc{.yml,.js,}`

J'étais étonné de voir que sans eslintrc, le linter ne sert à rien :

<img width="741" alt="screen shot 2017-01-24 at 13 56 55" src="https://cloud.githubusercontent.com/assets/138627/22248067/2ddad646-e23d-11e6-8820-f9c4736435da.png">

Quand y'a le fichier de config, ça produit des alertes comme celle-ci :

![image](https://cloud.githubusercontent.com/assets/138627/22248083/3caad4f0-e23d-11e6-8801-5a1d7547365d.png)

2017-01-24 13:03 UTC, oncletom commented
@DavidBruant fait. Il suit les [mêmes règles que `.gitignore`](http://eslint.org/docs/user-guide/configuring#using-an-alternate-file) comme ça, pas de double maintenance.

2017-01-25 16:18 UTC, DavidBruant commented
> Il suit les mêmes règles que .gitignore comme ça, pas de double maintenance.

Ok, ça divergera un jour, mais on verra quand on y sera.

2017-01-25 16:19 UTC, merged